/* credential_signature_patch.js — firma de directivos/administrativos */
(function(){
  var state=window.__piagetSignatureState=window.__piagetSignatureState||{draft:null,touched:false,current:null,byEmail:{},byName:{}};
  function remember(row){try{if(!row)return;var sig=row.signature_url||row.signature||row.signature_image||'';if(!sig)return;var email=String(row.email||row.username||'').toLowerCase();var name=String(row.name||'').trim();if(email)state.byEmail[email]=sig;if(name)state.byName[name]=sig;}catch(e){}}
  function patchClient(c){try{if(!c||c.__sigPatch||!c.rpc)return c;var orig=c.rpc.bind(c);c.rpc=function(name,args){var next=args;if(name==='piaget_account_upsert'&&args&&args.p_account&&state.touched){next=Object.assign({},args,{p_account:Object.assign({},args.p_account,{signature_url:state.draft||''})});}return orig(name,next).then(function(res){try{if(name==='piaget_accounts_read'&&res&&Array.isArray(res.data))res.data.forEach(remember);if(name==='piaget_account_upsert'&&res&&res.data)remember(res.data);}catch(e){}return res;});};c.__sigPatch=true;}catch(e){}return c;}
  function patchSupabase(){try{if(window.PIAGET_SB)patchClient(window.PIAGET_SB);if(window.PiagetSettings&&window.PiagetSettings.client&&!window.PiagetSettings.__sigPatch){var prev=window.PiagetSettings.client;window.PiagetSettings.client=function(){return prev.apply(this,arguments).then(patchClient);};window.PiagetSettings.__sigPatch=true;}}catch(e){}}
  function fileToData(file,cb){if(!file)return;if(!/^image\//.test(file.type)){if(window.toast)toast('Selecciona una imagen válida','warn');return;}var r=new FileReader();r.onload=function(){cb(r.result);};r.readAsDataURL(file);}
  function makeBox(modal){
    if(modal.querySelector('.piaget-signature-box'))return;
    var isCreate=/Crear usuario administrativo/i.test(modal.textContent||'');
    state.draft=null;state.touched=false;
    var current=isCreate?'':(state.current||'');
    var box=document.createElement('div');box.className='card pad piaget-signature-box';
    box.style.cssText='padding:14px;display:grid;gap:10px;border:1px solid var(--border);border-radius:var(--r);background:var(--surface);';
    box.innerHTML='<div><div style="font-weight:700;font-size:13.5px">Firma para credencial</div><div class="faint" style="font-size:12px">Sube una imagen de la firma o captúrala directamente en el pad.</div></div><div class="sig-preview" style="height:58px;border:1px dashed var(--border);border-radius:12px;background:#fff;display:grid;place-items:center;overflow:hidden;color:var(--text-faint);font-size:12px">Sin firma cargada</div><div class="row gap-8 wrap"><button type="button" class="btn sm sig-upload">Subir firma</button><button type="button" class="btn sm sig-pad">Capturar con pad</button><button type="button" class="btn sm sig-clear">Quitar</button></div><input type="file" accept="image/png,image/jpeg,image/webp" style="display:none" class="sig-file"><div class="sig-pad-wrap" style="display:none;gap:8px"><canvas width="520" height="160" style="width:100%;height:120px;background:#fff;border:1px solid var(--border);border-radius:12px;touch-action:none"></canvas><div class="row gap-8"><button type="button" class="btn sm sig-use">Usar firma</button><button type="button" class="btn sm sig-erase">Limpiar pad</button><button type="button" class="btn sm sig-cancel">Cancelar</button></div></div>';
    var preview=box.querySelector('.sig-preview'),file=box.querySelector('.sig-file'),wrap=box.querySelector('.sig-pad-wrap'),canvas=box.querySelector('canvas'),ctx=canvas.getContext('2d');
    ctx.lineCap='round';ctx.lineJoin='round';ctx.lineWidth=4;ctx.strokeStyle='#111827';
    function setSig(data,touched){state.draft=data||'';state.touched=!!touched;if(data)state.current=data;preview.innerHTML=data?'<img src="'+data+'" alt="Firma" style="max-width:96%;max-height:48px;object-fit:contain;object-position:center center">':'Sin firma cargada';}
    if(current)setSig(current,false);
    box.querySelector('.sig-upload').onclick=function(){file.click();};file.onchange=function(e){var f=e.target.files&&e.target.files[0];e.target.value='';fileToData(f,function(d){setSig(d,true);});};
    box.querySelector('.sig-clear').onclick=function(){setSig('',true);};box.querySelector('.sig-pad').onclick=function(){wrap.style.display='grid';ctx.clearRect(0,0,canvas.width,canvas.height);};box.querySelector('.sig-cancel').onclick=function(){wrap.style.display='none';};box.querySelector('.sig-erase').onclick=function(){ctx.clearRect(0,0,canvas.width,canvas.height);};box.querySelector('.sig-use').onclick=function(){setSig(canvas.toDataURL('image/png'),true);wrap.style.display='none';};
    var drawing=false,last=null;function pos(ev){var r=canvas.getBoundingClientRect(),p=ev.touches?ev.touches[0]:ev;return{x:(p.clientX-r.left)*canvas.width/r.width,y:(p.clientY-r.top)*canvas.height/r.height};}function down(ev){drawing=true;last=pos(ev);ev.preventDefault();}function move(ev){if(!drawing)return;var p=pos(ev);ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();last=p;ev.preventDefault();}function up(){drawing=false;last=null;}canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);window.addEventListener('pointerup',up);
    var photo=Array.prototype.slice.call(modal.querySelectorAll('*')).find(function(x){return /Foto para credencial/i.test(x.textContent||'');});var anchor=photo&&photo.closest('.card');if(anchor&&anchor.parentElement)anchor.parentElement.insertBefore(box,anchor.nextSibling);else modal.appendChild(box);
  }
  function signatureFor(text){text=String(text||'');var email=(text.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i)||[])[0];if(email&&state.byEmail[email.toLowerCase()])return state.byEmail[email.toLowerCase()];for(var name in state.byName){if(name&&text.indexOf(name)!==-1)return state.byName[name];}return state.current||'';}
  function injectSig(root){try{var sig=signatureFor(root.textContent||'');if(!sig)return;Array.prototype.slice.call(root.querySelectorAll('*')).forEach(function(el){if(String(el.textContent||'').trim()==='Firma del titular'){var line=el.nextElementSibling;if(!line&&el.parentElement)line=Array.prototype.slice.call(el.parentElement.children).find(function(x){return x!==el&&/border-bottom/i.test(x.getAttribute('style')||'');});if(line){line.style.backgroundImage='url('+sig+')';line.style.backgroundSize='contain';line.style.backgroundPosition='center center';line.style.backgroundRepeat='no-repeat';line.style.minHeight=line.style.minHeight||'30px';}}});}catch(e){}}
  function patchFrames(){document.querySelectorAll('iframe').forEach(function(frame){try{var doc=frame.contentDocument||(frame.contentWindow&&frame.contentWindow.document);if(doc)injectSig(doc.body||doc);frame.addEventListener('load',function(){setTimeout(function(){try{injectSig(frame.contentDocument.body);}catch(e){}},50);});}catch(e){}});}
  function patchPdf(){try{var ctor=window.jspdf&&window.jspdf.jsPDF;if(!ctor)return;[ctor.API,ctor.prototype].forEach(function(api){if(!api||api.__sigPdfPatch||!api.save)return;var orig=api.save;api.save=function(){try{var sig=state.current;if(sig&&!this.__sigAdded&&this.getNumberOfPages&&this.addImage){var cur=this.getCurrentPageInfo?this.getCurrentPageInfo().pageNumber:null;if(this.setPage)this.setPage(Math.min(2,this.getNumberOfPages()));this.addImage(sig,sig.indexOf('data:image/png')===0?'PNG':'JPEG',10,55.5,34,8,undefined,'FAST');if(cur&&this.setPage)this.setPage(cur);this.__sigAdded=true;}}catch(e){}return orig.apply(this,arguments);};api.__sigPdfPatch=true;});}catch(e){}}
  document.addEventListener('click',function(e){var btn=e.target.closest&&e.target.closest('button');if(!btn)return;var txt=btn.textContent||'';if(/Ver credencial|Editar foto|Editar usuario/i.test(txt)){var tr=btn.closest('tr');if(tr){var rowtxt=tr.textContent||'',email=(rowtxt.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i)||[])[0],name=(tr.querySelector('.pname')&&tr.querySelector('.pname').textContent.trim())||'';state.current=(email&&state.byEmail[email.toLowerCase()])||(name&&state.byName[name])||'';}}});
  function tick(){patchSupabase();patchPdf();document.querySelectorAll('body *').forEach(function(el){var tx=el.textContent||'';if((/Crear usuario administrativo|Editar usuario administrativo/i.test(tx))&&!el.querySelector('.piaget-signature-box'))makeBox(el);});document.querySelectorAll('.jp-card,.p,.c').forEach(injectSig);patchFrames();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){tick();setInterval(tick,700);});else{tick();setInterval(tick,700);} 
})();
