/* student_credentials_patch.js — acceso de estudiantes + credencial imprimible */
(function(){
  function clean(v){ return String(v||'').trim().replace(/\s+/g,' '); }
  function slug(v){ return clean(v).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ñ/g,'n').replace(/[^a-z0-9]/g,''); }
  function parts(name){ var p=clean(name).split(' ').filter(Boolean); return { first:p[0]||'', second:p.length>3?p[1]:'', paternal:p.length>=3?p[p.length-2]:(p[1]||''), maternal:p.length>=3?p[p.length-1]:'' }; }
  function studentEmail(name, existingId){ var n=parts(name); if(!n.first||!n.paternal) return ''; var base=slug(n.first)+(n.second?slug(n.second).slice(0,1):'')+slug(n.paternal)+(n.maternal?slug(n.maternal).slice(0,1):''); var used=new Set(((window.DB&&DB.students)||[]).filter(function(s){return s._id!==existingId;}).map(function(s){return String(s.email||'').toLowerCase();}).filter(Boolean)); var email=base+'@jeanpiaget.mx', i=2; while(used.has(email)){ email=base+i+'@jeanpiaget.mx'; i++; } return email; }
  function makeKey(name, curp){ var a=(slug(parts(name).first).slice(0,4)||'jpgt'); var b=(slug(curp).slice(-4)||'2026').toUpperCase(); return a.charAt(0).toUpperCase()+a.slice(1)+b+String(Math.floor(100+Math.random()*900)); }
  function accounts(){ window.DB=window.DB||{}; DB.settings=DB.settings||{}; DB.settings.studentAccounts=Array.isArray(DB.settings.studentAccounts)?DB.settings.studentAccounts:[]; return DB.settings.studentAccounts; }
  function upsert(student){ var list=accounts(); var old=list.find(function(a){return a.studentId===student._id||String(a.email||'').toLowerCase()===String(student.email||'').toLowerCase();}); var key=student.accessKey||(student.access&&student.access.key)||makeKey(student.name,student.curp); var acc={ id:old?old.id:'stuacc-'+Date.now(), studentId:student._id, name:student.name, email:student.email, username:student.email, key:key, role:'Estudiante', kind:'student', vista:'home', status:'Activo', createdAt:old?old.createdAt:new Date().toISOString(), updatedAt:new Date().toISOString() }; DB.settings.studentAccounts=old?list.map(function(a){return (a.id===old.id||a.studentId===student._id)?acc:a;}):[acc].concat(list); return acc; }
  function installAuth(){ window.AUTH_RESOLVERS=window.AUTH_RESOLVERS||[]; if(!window.AUTH_RESOLVERS.some(function(r){return r&&r.__jpStudent;})){ var resolver=function(id, secret){ var acc=accounts().find(function(a){return String(a.status||'Activo')==='Activo'&&[a.email,a.username,a.studentId].map(function(x){return String(x||'').toLowerCase();}).indexOf(String(id||'').toLowerCase())>=0;}); if(!acc) return null; if(String(acc.key||'')!==String(secret||'')) return {ok:false,error:'Usuario o contraseña incorrectos.'}; return {name:acc.name,role:'Estudiante',email:acc.email,kind:'student',vista:'home',students:[acc.studentId],studentId:acc.studentId}; }; resolver.__jpStudent=true; window.AUTH_RESOLVERS.push(resolver); }
    if(window.PiagetAuth&&!window.PiagetAuth.__jpStudentFallback){ var original=window.PiagetAuth.authenticate; window.PiagetAuth.authenticate=async function(id,secret){ var r=original?await original(id,secret):{ok:false}; if(r&&r.ok) return r; for(var i=0;i<(window.AUTH_RESOLVERS||[]).length;i++){ var local=(window.AUTH_RESOLVERS[i])(String(id||'').toLowerCase(),String(secret||'')); if(local&&local.ok===false) return local; if(local) return {ok:true,account:local}; } return r; }; window.PiagetAuth.__jpStudentFallback=true; }
  }
  function printCredential(stu){ var photo=stu.photo||''; var qr=''; try{ if(window.qrcode){ var q=qrcode(0,'M'); q.addData(stu.matricula||stu._id||stu.email); q.make(); qr=q.createDataURL(5,0); } }catch(_){} var html='<!doctype html><html><head><meta charset="utf-8"><title>Credencial '+clean(stu.name)+'</title><style>@page{size:86mm 54mm;margin:0}*{box-sizing:border-box}body{margin:0;background:#0b1a57;font-family:Arial,sans-serif;display:grid;place-items:center;min-height:100vh}.id{width:86mm;height:54mm;background:#fff;border-radius:6mm;overflow:hidden;position:relative;box-shadow:0 16px 40px rgba(0,0,0,.28)}.top{height:16mm;background:#0b1a57;color:#fff;padding:4mm 5mm;display:flex;align-items:center;gap:3mm}.logo{width:10mm;height:10mm;border-radius:50%;background:#0e27e6;display:grid;place-items:center;font-weight:900;font-size:7mm}.brand{font-weight:900;font-size:5mm;letter-spacing:.04em}.sub{font-size:2.5mm;opacity:.9}.body{display:flex;padding:4mm 5mm;gap:4mm}.photo{width:23mm;height:28mm;border-radius:4mm;background:#e8ecff;overflow:hidden;border:1px solid #d6dbff}.photo img{width:100%;height:100%;object-fit:cover}.name{font-size:4.3mm;font-weight:900;color:#0b1a57;line-height:1.05;text-transform:uppercase}.row{font-size:2.65mm;color:#26345e;margin-top:1.3mm}.lbl{font-weight:800;color:#0b1a57}.qr{position:absolute;right:5mm;bottom:4mm;width:15mm;height:15mm}.bar{position:absolute;left:0;right:0;bottom:0;height:2mm;background:#0e27e6}@media print{body{background:#fff}.id{box-shadow:none}}</style></head><body><div class="id"><div class="top"><div class="logo">P</div><div><div class="brand">PIAGET</div><div class="sub">CREDENCIAL ESTUDIANTE</div></div></div><div class="body"><div class="photo">'+(photo?'<img src="'+photo+'">':'')+'</div><div style="flex:1;min-width:0"><div class="name">'+clean(stu.name)+'</div><div class="row"><span class="lbl">Matrícula:</span> '+(stu.matricula||'—')+'</div><div class="row"><span class="lbl">Nivel:</span> '+(stu.nivel||'—')+'</div><div class="row"><span class="lbl">Grupo:</span> '+(stu.grade||stu.group||'—')+'</div><div class="row"><span class="lbl">CURP:</span> '+(stu.curp||'—')+'</div><div class="row"><span class="lbl">Correo:</span> '+(stu.email||'—')+'</div></div></div>'+(qr?'<img class="qr" src="'+qr+'">':'')+'<div class="bar"></div></div></body></html>'; var w=window.open('','_blank'); if(!w){ if(window.toast) toast('Permite ventanas emergentes para imprimir la credencial','warn'); return; } w.document.open(); w.document.write(html); w.document.close(); setTimeout(function(){try{w.print();}catch(_){ }},300); }
  installAuth();
  window.jpStudentEmail=studentEmail; window.jpStudentKey=makeKey; window.jpUpsertStudentAccount=upsert; window.jpStudentAccounts=accounts; window.jpPrintCredential=printCredential;
})();